# Generated by Django 3.2.5 on 2021-12-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_book_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book_table',
            new_name='register_user',
        ),
    ]
