# Generated by Django 3.2.5 on 2021-12-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_rename_book_table_register_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_user',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
